# Generated by Django 5.0.7 on 2024-08-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transient_type', models.CharField(max_length=20)),
                ('obs_or_lim', models.BooleanField()),
                ('DataTime', models.DateTimeField()),
                ('Ra', models.FloatField()),
                ('Dec', models.FloatField()),
                ('max_limit', models.IntegerField()),
                ('max_magnitude', models.IntegerField()),
                ('lightcurve', models.CharField(max_length=300, default = 'http://observ.pereplet.ru/')),
                ('pictures', models.ImageField(upload_to='')),
                ('telescope', models.CharField(max_length=30, default = 'MASTER')),
                ('publication', models.CharField(max_length=300, default = 'http://observ.pereplet.ru/')),
                ('if_we_first', models.BooleanField()),
                ('time_from_notice', models.IntegerField()),
                ('sattelite', models.IntegerField(default = 'MASTER')),
            ],
        ),
    ]
