# Generated by Django 5.0.7 on 2024-08-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_observation_discoverer_observation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='Dec',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='observation',
            name='Ra',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='observation',
            name='discoverer',
            field=models.CharField(default='Lipunov V. M.', max_length=30),
        ),
        migrations.AlterField(
            model_name='observation',
            name='if_we_first',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='observation',
            name='lightcurve',
            field=models.CharField(default='http://observ.pereplet.ru/', max_length=300),
        ),
        migrations.AlterField(
            model_name='observation',
            name='max_limit',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='observation',
            name='max_magnitude',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_or_lim',
            field=models.CharField(default='l', max_length=1),
        ),
        migrations.AlterField(
            model_name='observation',
            name='pictures',
            field=models.ImageField(default='http://observ.pereplet.ru/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='observation',
            name='publication',
            field=models.CharField(default='http://observ.pereplet.ru/', max_length=300),
        ),
        migrations.AlterField(
            model_name='observation',
            name='sattelite',
            field=models.CharField(default='MASTER', max_length=30),
        ),
        migrations.AlterField(
            model_name='observation',
            name='telescope',
            field=models.CharField(default='MASTER', max_length=30),
        ),
        migrations.AlterField(
            model_name='observation',
            name='time_from_notice',
            field=models.IntegerField(default=0),
        ),
    ]
