# Generated by Django 5.0.7 on 2024-08-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_observation_dec_alter_observation_ra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='Ra',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='transient_type',
            field=models.CharField(default='OT', max_length=200),
        ),
    ]
