# Generated by Django 5.0.7 on 2024-08-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_observation_ra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='Dec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='max_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='max_magnitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='time_from_notice',
            field=models.IntegerField(null=True),
        ),
    ]
