# Generated by Django 5.0.7 on 2024-09-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_observation_dec_alter_observation_max_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='sattelite',
            new_name='satellite',
        ),
    ]
